### ISSUE TITLE
We're still processing your most recent tip /tip Bug!

### ISSUE THREAD

**Issue by HIQEA** [Semx11/Autotip#4]
![image](https://user-images.githubusercontent.com/24274668/27002208-e100b81c-4ddb-11e7-84a4-21edce26ec4a.png)

**Comment by Semx11** [comment]
This issue seems to be a server-side problem with the recent change so that you can't tip offline users who don't have a Network booster active.
If you try to tip someone who is offline, it apparently doesn't fully process the tip, and gives this message.
We will wait and see what happens next, but thank you for reporting :)

**Comment by boomboompower** [comment]
@Semx11 for now maybe just cancel the event if it matches that message?

**Comment by Semx11** [comment]
@boomboompower That would've required a client update, something we rather avoid, but thanks for the suggestion!

Currently working on Autotip 2.1 which will fix the "offline player" issue, the "processing most recent tip" issue has already been fixed by Hypixel.
